version: '3'
services:
  api:
    build: ./api
    environment:
      - PORT=5001
    ports:
      - '5001:5001'
  app:
    build: ./app
    depends_on:
      - api
    environment:
      - API_URL=http://localhost:5001
    ports:
      - '5000:5000'
